-- Migration: add public_id to trusted_devices (safe)

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE;
SET SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

ALTER TABLE trusted_devices
    ADD COLUMN IF NOT EXISTS `public_id` CHAR(36) NULL AFTER `id`;

ALTER TABLE trusted_devices
    ADD UNIQUE INDEX IF NOT EXISTS `ux_public_id` (`public_id`);

ALTER TABLE trusted_devices
    ADD INDEX IF NOT EXISTS `idx_user_public` (`user_type`,`user_id`,`public_id`);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;